### ISSUE TITLE
News Base URL Changed?

### ISSUE THREAD

**Issue by lovebdsobuj** [dmytroKarataiev/EarthquakeSurvival#5]
[NEWS_BASE_URL](http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/) - 404 Not Found

**Comment by dmytroKarataiev** [comment]
It's just a dummy url, because you are not allowed to have an empty string. But you can provide a completely new url in a Service: https://github.com/dmytroKarataiev/EarthquakeSurvival/blob/master/app/src/main/java/com/adkdevelopment/earthquakesurvival/remote/EarthquakeService.java#L45

**Comment by lovebdsobuj** [comment]
Application forced closed.
Android : 4.4.2 (19) KITKAT.
Device : Nox Android Player.

**Comment by dmytroKarataiev** [comment]
Thank you, I will check several 4+ devices today and let you know of the results.

**Comment by lovebdsobuj** [comment]
I installed few times ago. 
Please check this https://gist.github.com/lovebdsobuj/2fbb1b49a2b49a99bd67fa374804d9b0

**Comment by dmytroKarataiev** [comment]
Is it a real device or an emulator? I just made a few minor fixes, could you please try it now? But they are not related to the above posted issue...

**Comment by lovebdsobuj** [comment]
Actually, My 1st post and your 1st reply one topic. 

And my 2nd post about issue.

> Is it a real device or an emulator?
> It's an emulator.

But working well others apps in this emulator.

**Comment by dmytroKarataiev** [comment]
I think I may have found a problem. Can you try it now? 
Where can I download this emulator?

**Comment by lovebdsobuj** [comment]
Can be found here - [Nox APP Player_Best APP Player Ever](http://en.bignox.com/)

**Comment by dmytroKarataiev** [comment]
Direct download link to the apk file: https://www.dropbox.com/s/lw7pgj2xxghoj4u/app-release.apk?dl=0

**Comment by dmytroKarataiev** [comment]
Commits for this issue:
273152ca9716784be0d6c892366495b50e48a303
9a86de2537ba9c93f1cd508ac0e15e788000c144

**Comment by lovebdsobuj** [comment]
Still forced closed. [NewLogcat](https://gist.github.com/lovebdsobuj/2fbb1b49a2b49a99bd67fa374804d9b0#file-newlogcat)

**Comment by dmytroKarataiev** [comment]
Can you try it again please with this new APK? (I can't install this emulator as I don't have windows devices).
https://www.dropbox.com/s/lw7pgj2xxghoj4u/app-release.apk?dl=0

**Comment by lovebdsobuj** [comment]
> I can't install this emulator as I don't have windows devices
> No problem...

**Comment by lovebdsobuj** [comment]
Now App Exit after start listing news item - [Logcat03](https://gist.github.com/lovebdsobuj/2fbb1b49a2b49a99bd67fa374804d9b0#file-logcat03-md)
You can see this video - https://dl.dropboxusercontent.com/1/view/wvt6r8b1dwfwp5x/Video/untitled2.mp4?dl=0

**Comment by dmytroKarataiev** [comment]
Yes, I've found the problem and I think it is because of the emulator specific implementation. 
It crashes because it doesn't have an ActivityOptions.makeSceneTransitionAnimation method (and several others), which is available in all devices starting from LOLLILOP. I can only solve it by deleting it from the app, which I don't want to do.
This version should work fine (I deleted all the calls to SharedTransitions): 
[app-release.apk.zip](https://github.com/dmytroKarataiev/EarthquakeSurvival/files/254022/app-release.apk.zip)

**Comment by dmytroKarataiev** [comment]
[app-release.apk.zip](https://github.com/dmytroKarataiev/EarthquakeSurvival/files/254022/app-release.apk.zip)

**Comment by lovebdsobuj** [comment]
Apps is now working :)

**Comment by lovebdsobuj** [comment]
If android version isn't LOLIPOP >5, then they would face same problem?

**Comment by dmytroKarataiev** [comment]
The main problem is that this emulator doesn't have several methods which are present in the API starting from LOLLILOP and they MUST be implemeted (otherwise you shouldn't say that your device is running Android 4.4+ version):
- android.app.ActivityOptions.makeSceneTransitionAnimation
- android.view.ViewAnimationUtils.createCircularReveal
- android.content.res.Resources.getDrawable
- android.view.View.getTransitionName
